/* tslint:disable */
/* eslint-disable */

/* auto-generated by NAPI-RS */

export declare function sum(a: number, b: number): number
export declare function encodeImage(rawData: Uint8Array): ImageWithHashes
export declare class ImageWithHashes {
  png: Uint8Array
  minecraftHash: Uint8Array
  hash: Uint8Array
}
